---
# file: site.yml
- name: main playbook
  hosts: web
  vars:
    db_password: "secret"
    opentrv_repo_url: https://github.com/dvoong/opentrv
  tasks:
    - name: install apt packages
      apt: pkg={{ item }} update_cache=yes cache_valid_time=3600
      sudo: True
      with_items:
        - git
        - nginx
        - postgresql
        - python-dev
        - python-pip
        - python-psycopg2
        - libpq-dev
        - python-virtualenv
        - lib32ncurses5-dev

    - name: create opentrv group
      group: name=opentrv state=present gid=510
      sudo: True

    - name: create opentrv user
      user: name=opentrv group=opentrv uid=510 groups=sudo append=yes
      sudo: True

    - name: create opentrv directory
      file: path=/srv/opentrv state=directory owner=opentrv group=opentrv
      sudo: True

    # get the code here. Use git hub for a remote host or let the vm do the shared folder thing
    # if no source directory exists do a git clone else do a git pull
    - name: check out the repository on the host
      git: repo=https://github.com/dvoong/opentrv dest=/srv/opentrv/source accept_hostkey=yes
      become: yes
      become_user: opentrv
      when: use_git
      notify:
        - restart gunicorn
        - restart udp_server

    - name: create database directory
      file: path=/srv/opentrv/database state=directory group=opentrv
      become: yes
      become_user: opentrv

    - name: create logs directory
      file: path=/srv/opentrv/logs state=directory group=opentrv
      become: yes
      become_user: opentrv
      
    - name: install required python packages
      pip: requirements=/srv/opentrv/source/requirements.txt virtualenv=/srv/opentrv/virtualenv
      become: yes
      become_user: opentrv

    - name: create postgres user
      postgresql_user:
        name: opentrv
        password: "{{ db_password }}"
        role_attr_flags: CREATEDB
      sudo: True
      sudo_user: postgres

    - name: create the postgres database
      postgresql_db:
        name: "opentrv_db"
        owner: opentrv
        encoding: UTF8
      sudo: True
      sudo_user: postgres

    - name: sync the database, apply migrations, collect static content         
      django_manage:
        command: "{{ item }}"
        app_path: "/srv/opentrv/source"
        virtualenv: "/srv/opentrv/virtualenv"
      with_items:
        - migrate
	- collectstatic
      become: yes
      become_user: opentrv

    - name: setup gunicorn configuration
      template: src=../templates/gunicorn.conf.j2 dest=/etc/init/opentrv_gunicorn.conf
      notify: restart gunicorn
      sudo: True

    - name: set the nginx config file
      template: src=../templates/nginx.conf.j2 dest=/etc/nginx/sites-available/opentrv
      notify: restart nginx
      sudo: True

    - name: enable opentrv in nginx
      file:
        dest: /etc/nginx/sites-enabled/opentrv
        src: /etc/nginx/sites-available/opentrv
        state: link
      sudo: True
      notify: restart nginx

    - name: delete nginx default config file
      file: path=/etc/nginx/sites-enabled/default state=absent
      notify: restart nginx
      sudo: True

    - name: configure the udp server
      template: src=../templates/udp_server.conf.j2 dest=/etc/init/udp_server.conf
      notify: restart udp_server
      sudo: True

  handlers:
    - name: restart nginx
      service: name=nginx state=restarted
      sudo: True

    - name: restart gunicorn
      service: name=opentrv_gunicorn state=restarted
      sudo: True

    - name: restart udp_server
      service: name=udp_server state=restarted
      sudo: True